# Copyright 2026 Feralthedogg
# SPDX-License-Identifier: Apache-2.0

if(NOT DEFINED LLAM_BUILD_PROVENANCE_PATH)
    message(FATAL_ERROR "LLAM_BUILD_PROVENANCE_PATH is required")
endif()
if(NOT LLAM_BUILD_RESEARCH_MODE MATCHES "^[01]$")
    message(FATAL_ERROR "LLAM_BUILD_RESEARCH_MODE must be 0 or 1")
endif()

set(LLAM_BUILD_PROVENANCE_TEMP
    "${LLAM_BUILD_PROVENANCE_PATH}.tmp")
file(WRITE "${LLAM_BUILD_PROVENANCE_TEMP}"
     "LLAM_BUILD_RESEARCH=${LLAM_BUILD_RESEARCH_MODE}\n")
file(RENAME "${LLAM_BUILD_PROVENANCE_TEMP}"
     "${LLAM_BUILD_PROVENANCE_PATH}")
